name: Vercel Preview

on:
  pull_request:
    branches: [ main ]

jobs:
  preview:
    runs-on: ubuntu-latest
    if: ${{ env.VERCEL_TOKEN != '' && env.VERCEL_ORG_ID != '' && env.VERCEL_PROJECT_ID != '' }}
    defaults:
      run:
        working-directory: web
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Pull Vercel environment
        run: npx vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}
      - name: Build with Vercel
        run: npx vercel build --token=${{ env.VERCEL_TOKEN }}
      - name: Deploy to Vercel (Preview)
        run: npx vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }}
